### ISSUE TITLE
[ProxyMan] Add support for `.zshrc`

### ISSUE THREAD

**Issue by himanshub16** [fossiiita/Projects#12]
[Original issue.](https://github.com/himanshub16/ProxyMan/issues/10)
zshrc is not configured as of now.

**Comment by gauthamzz** [comment]
This is a nice idea , why don't we open issue for every type of shell as well , even the unpopular ones

**Comment by himanshub16** [comment]
Shall I close all the issues then?

**Comment by gauthamzz** [comment]
Yeah

**Comment by himanshub16** [comment]
Not required. Because most of them conform and support one another. Moreover, `bash` is supported by the operating system, irrespective of your shell. 
I thought of `zsh` after finding out that most of the Mac users are accustomed to zsh because Apple provides really poor terminal and outdated bash.
`zsh` and `bash` are enough.
