### ISSUE TITLE
[ProxyMan] Add feature to set proxy settings temporarily.

### ISSUE THREAD

**Issue by himanshub16** [fossiiita/Projects#13]
[Original issue]( https://github.com/himanshub16/ProxyMan/issues/9).
This is something to be carefully figured out. The aim is to reset old settings on logout.
It is required when the user is on a public terminal/computer lab, where there are chances to forget removing values, and sometimes passwords.

**Comment by gauthamzz** [comment]
Why don't we just configure it via export then , so when session is over. It will be removed ?

**Comment by himanshub16** [comment]
Then the applications which you would run like the browser, or other user apps need to be started from the same terminal window.

**Comment by himanshub16** [comment]
Please comment on the the main repo. I'm closing these issues.
