### ISSUE TITLE
[ProxyMan] Use .bash_profile instead of .bashrc if the user has a login shell.

### ISSUE THREAD

**Issue by himanshub16** [fossiiita/Projects#15]
[Original issue](https://github.com/himanshub16/ProxyMan/issues/7).
Many times the user has a login shell instead of a normal shell, like MacOS, servers. In that case, the environment variables are available in .bash_profile instead of .bashrc.
A fix is required around this, by checking which of those two files already exist and try to change settings for that only.

**Comment by gauthamzz** [comment]
Keep one issue of the projects name , all the rest put in the proxy man main repo :+1 thanks :) we don't want to duplicate things .

**Comment by himanshub16** [comment]
Shall I close all the issues then?

**Comment by gauthamzz** [comment]
Yeah .
