### ISSUE TITLE
[ProxyMan] Colors don't display on MacOS.

### ISSUE THREAD

**Issue by himanshub16** [fossiiita/Projects#16]
[Original issue](https://github.com/himanshub16/ProxyMan/issues/6)
The default terminal/bash in MacOS does not support colours, which makes the terminal display the colour codes adjoining the exact statement. This could even happen on old terminal emulators which don't support colour. (not tested yet)
The solution is to have some workaround this, by having a separate script without any such colour codes and executing that if things start to fail.

**Comment by gauthamzz** [comment]
Can you keep ask issues over at main repo
